#ifndef CACHE_LIST_SETTINGS_H
#define CACHE_LIST_SETTINGS_H

#define NDEBUG
#define NVERIFY

#define LOG_NTRACE
#define LOG_NLEAK
//#define LOG_NDEBUG
//#define LOG_NVERIFY

//#define CACHE_LIST_NVERIFY
//#define CACHE_LIST_NDEBUG

#endif //CACHE_LIST_SETTINGS_H